export default {
  GET_STUDENTS: 'GET_STUDENTS',
  ADD_STUDENT: 'ADD_STUDENT',
  DELETE_STUDENT_BY_ID: 'DELETE_STUDENT_BY_ID',
  GET_STUDENT_BY_ID: 'GET_STUDENT_BY_ID',
  GET_RESULTS: 'GET_RESULTS',
  GET_STUDENT_RESULTS: 'GET_STUDENT_RESULTS',
  GET_EXAMS: 'GET_EXAMS',
  GET_EXAM_BY_ID: 'GET_EXAM_BY_ID',
  GET_DEFAULT_EXAM: 'GET_DEFAULT_EXAM',
  ADD_EXAM: 'ADD_EXAM',
  UPDATE_EXAM: 'UPDATE_EXAM',
};
