export default {
  GET_STUDENTS: 'GET_STUDENTS',
  ADD_STUDENT: 'ADD_STUDENT',
  GET_STUDENT_BY_ID: 'GET_STUDENT_BY_ID',
  GET_EXAMS: 'GET_EXAMS',
  GET_EXAM_BY_ID: 'GET_EXAM_BY_ID',
  GET_DEFAULT_EXAM: 'GET_DEFAULT_EXAM',
};
