export default {
  SET_LOADER: 'SET_LOADER',
  ADD_STUDENT: 'ADD_STUDENT',
  SET_STUDENTS: 'SET_STUDENTS',
  SET_CURRENT_STUDENT: 'SET_CURRENT_STUDENT',
  SET_CURRENT_EXAM: 'SET_CURRENT_EXAM',
  SET_EXAMS: 'SET_EXAMS',
};
